FROM ubuntu:16.04


RUN apt-get update
RUN apt-get -y install build-essential gcc-multilib git-core gdb libsdl1.2-dev libtool-bin libglib2.0-dev libz-dev libpixman-1-dev 
RUN git clone http://web.mit.edu/ccutler/www/qemu.git -b 6.828-2.3.0
RUN cd qemu && ./configure --disable-kvm --target-list="i386-softmmu x86_64-softmmu" && make && make install
RUN git clone git://github.com/mit-pdos/xv6-public.git
RUN cd xv6-public && make
